*** Settings ***
Library    SeleniumLibrary

*** Variables ***
${MORE_ICON_XPATH}        (//button[@class="ant-btn css-xogyor css-var-_r_0_ ant-btn-text ant-btn-color-default ant-btn-variant-text ant-btn-sm ant-btn-icon-only ant-dropdown-trigger"])[1]
${VIEW_XPATH}             //li[@data-menu-id="rc-menu-uuid-view"]
${LEADS_PAGE_XPATH}        //h2[text()='Leads']
${BACK_IOCN_XPATH}          (//button[@class="ant-btn css-xogyor css-var-_r_0_ ant-btn-text ant-btn-color-default ant-btn-variant-text ant-btn-icon-only"])[5]
